public class problem2 {
    /*
    Write a complete ISBN class, including the
    constructor and any required instance
    variables and methods.
    - The ISBN object provides two methods:
      - calculateCheckDigit
        - Performs calculations to determine
          check digit.
      - generateNumber
        - Joins the nine-digit number and
          the check digit generated by
          calculateCheckDigit
     */

    //All above this line are provided by the test.

    public static class ISBN {
        String num;
        public ISBN(int num) {
            this.num = String.valueOf(num);
        }
        public String calculateCheckDigit() {
            int a = 0;
            for (int i = 0; i < num.length(); i++) {
                a+= Integer.parseInt(num.substring(i, i+1))*(10-i);
            }
            return 11 - (a % 11) == 10 ? "X" : String.valueOf(11 - (a%11));
        }

        public String generateNumber() {
            return num+"-"+calculateCheckDigit();
        }
    }
}
